stages:
  - build
  - telegram

build-backend-code-job:
  stage: build
  only:
    changes:
    - backend/*
  script:
    - echo GE_JOB_ID=$CI_JOB_ID >> backend_job_id.env
    - cd backend
    - mvn package
  artifacts:
    name: release-backend
    paths:
      - backend/target/sausage-store-0.0.1-SNAPSHOT.jar
    reports:
      dotenv: backend_job_id.env

build-frontend-code-job:
  stage: build
  only:
    changes:
    - frontend/*
  script:
    - echo GE_JOB_ID=$CI_JOB_ID >> frontend_job_id.env
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    name: release-frontend
    paths:
      - frontend/dist/frontend
    reports:
      dotenv: frontend_job_id.env

telegram-notification-backend:
  stage: telegram
  variables:
    ARTIFACT_URL: "$GE_JOB_ID/artifacts/download?file_type=archive"
  script:
    - echo "send backend CURL"
    - echo "$ARTIFACT_URL"
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /^send notification/
  needs:
    - build-backend-code-job
