stages:
  - build
  - release

variables:
  VERSION: 1.0.${CI_PIPELINE_ID}


# <--------------- Stage 1: Build ---------------------->

build-backend-code-job:
  stage: build
  script:
    - cd backend
    - mvn package -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/.m2/


# <--------------- Stage 3: Release --------------------->

upload-backend-release:
  stage: release
  needs:
    - build-backend-code-job
  script:
    - cd backend
    - mvn clean deploy -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository -s settings.xml -Dversion.application=${VERSION} -Dmaven.test.skip=true
