stages:
  - build
  - telegram

build-backend-code-job:
  stage: build
  only:
    changes:
    - backend/*
  script:
    - cd backend
    - mvn package
  artifacts:
    paths:
      - backend/target/sausage-store-0.0.1-SNAPSHOT.jar

build-frontend-code-job:
  stage: build
  only:
    changes:
    - frontend/*
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/dist/frontend

telegram-notification-backend:
  stage: notify
  only:
    changes:
    - backend/*
  script:
    - echo "send backend CURL"
    - |
      curl --fail --output "/dev/null" --silent --show-error --write-out "HTTP response: ${http_code}\n\n" \
        --data "{\"chat_id\": \"${TELEGRAM_CHAT_ID}\", \"text\": \"[Зимин Николай] собрал backend ${CI_COMMIT_TAG}\"}" \
        --header "Content-Type: application/json" \
        --request POST \
        "https://api.telegram.org/${TELEGRAM_PRIVATE_TOKEN}/sendMessage"
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /^send notification/
  needs:
    - build-backend-code-job

telegram-notification-frontend:
  stage: notify
  only:
    changes:
    - frontend/*
  script:
    - echo "send frontend CURL"
    - |
      curl --fail --output "/dev/null" --silent --show-error --write-out "HTTP response: ${http_code}\n\n" \
        --data "{\"chat_id\": \"${TELEGRAM_CHAT_ID}\", \"text\": \"[Зимин Николай] собрал frontend ${CI_COMMIT_TAG}\"}" \
        --header "Content-Type: application/json" \
        --request POST \
        "https://api.telegram.org/${TELEGRAM_PRIVATE_TOKEN}/sendMessage"
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /^send notification/
  needs:
    - build-frontend-code-job