stages:
  - build
  - telegram

build-backend-code-job:
  stage: build
  only:
    changes:
    - backend/*
  script:
    - echo GE_JOB_ID=$CI_JOB_ID >> backend_job_id.env
    - cd backend
    - mvn package
  artifacts:
    name: release-backend
    paths:
      - backend/target/sausage-store-0.0.1-SNAPSHOT.jar
    reports:
      dotenv: backend_job_id.env

build-frontend-code-job:
  stage: build
  only:
    changes:
    - frontend/*
  script:
    - echo GE_JOB_ID=$CI_JOB_ID >> frontend_job_id.env
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    name: release-frontend
    paths:
      - frontend/dist/frontend
    reports:
      dotenv: frontend_job_id.env

telegram-notification-backend:
  stage: telegram
  variables:
    ARTIFACT_URL: "$CI_PROJECT_URL/-/jobs/$GE_JOB_ID/artifacts/download?file_type=archive"
  script:
    - echo "send backend CURL"
    - |
      curl --fail --output "/dev/null" --silent --show-error --write-out "HTTP response: ${http_code}\n\n" \
        --data "{\"chat_id\": \"${TELEGRAM_CHAT_ID}\", \"text\": \"[Зимин Николай] собрал backend ${ARTIFACT_URL}\"}" \
        --header "Content-Type: application/json" \
        --request POST \
        "https://api.telegram.org/${TELEGRAM_PRIVATE_TOKEN}/sendMessage"
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /^send notification/
  needs:
    - build-backend-code-job

telegram-notification-frontend:
  stage: telegram
  variables:
    ARTIFACT_URL: "$CI_PROJECT_URL/-/jobs/$GE_JOB_ID/artifacts/file/$release-frontend"
  script:
    - echo "send frontend CURL"
    - |
      curl --fail --output "/dev/null" --silent --show-error --write-out "HTTP response: ${http_code}\n\n" \
        --data "{\"chat_id\": \"${TELEGRAM_CHAT_ID}\", \"text\": \"[Зимин Николай] собрал frontend ${ARTIFACT_URL}\"}" \
        --header "Content-Type: application/json" \
        --request POST \
        "https://api.telegram.org/${TELEGRAM_PRIVATE_TOKEN}/sendMessage"
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /^send notification/
  needs:
    - build-frontend-code-job