stages:
  - build
  - telegram

build-backend-code-job:
  stage: build
  only:
    changes:
    - backend/*
  script:
    - cd backend
    - mvn package
  artifacts:
    name: release-backend
    paths:
      - backend/target/sausage-store-0.0.1-SNAPSHOT.jar

build-frontend-code-job:
  stage: build
  only:
    changes:
    - frontend/*
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    name: release-frontend
    paths:
      - frontend/dist/frontend

telegram-notification-backend:
  stage: telegram
  variables:
    ARTIFACT_URL: "$CI_JOB_URL/artifacts/download?file_type=archive"
  script:
    - echo "send backend CURL"
    - echo "CI_PIPELINE_URL"
    - echo "CI_ENVIRONMENT_URL"
    - echo "CI_PAGES_URL"
    - echo "CI_PROJECT_URL"
    - echo "CI_REPOSITORY_URL"
    - echo "CI_SERVER_URL"
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /^send notification/
  needs:
    - build-backend-code-job
