version: "3.3"

services:
  backend:
    image: gitlab.praktikum-services.ru:5050/std-017-003/sausage-store/sausage-backend:latest
    container_name: sausage-store-backend
    env_file: .env
    networks:
      - sausage-store
    environment:
      - VIRTUAL_HOST=backend
      - VIRTUAL_PORT=8080
  backend-report:
    image: gitlab.praktikum-services.ru:5050/std-017-003/sausage-store/sausage-backend-report:latest
    container_name: sausage-store-backend-report
    env_file: .env
    environment:
      - DEFAULT_HOST=backend-report
    networks:
      - sausage-store
  loadbalancer:
    image: gitlab.praktikum-services.ru:5050/std-017-003/sausage-store/sausage-frontend:latest
    container_name: sausage-store-frontend
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
    environment:
      - DEFAULT_HOST=backend
    networks:
      - sausage-store

networks:
  sausage-store: